targets:
  $default:
    builders:
      freezed:freezed:
        generate_for:
          include:
            - lib/src/model/**.dart
        options:
          map:
            map: false
            map_or_null: false
            maybe_map: false
          when:
            when: false
            when_or_null: false
            maybe_when: false
