targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      freezed:freezed:
        generate_for:
          include:
            - lib/src/model/**.dart
            - lib/src/service/google_place/**.dart
        options:
          map:
            map: false
            map_or_null: false
            maybe_map: false
          when:
            when: false
            when_or_null: false
            maybe_when: false
